from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT_DIR / "notebook_previews"
NOTEBOOKS = (
    "M1_EXPLORE.ipynb",
    "M2_CET_BUG.ipynb",
    "M3_COPILOT_INSTRUCTIONS.ipynb",
    "M4_TDD_VALIDATOR.ipynb",
    "M5_SODA.ipynb",
    "M6_VIBE_CODING.ipynb",
)
SHELL_LINE_RE = re.compile(
    r"^(cd|cp|echo|env|export|git|ls|mkdir|mv|pip|pytest|python[0-9.]*|quarto|rm|source)\b"
)
HEADING_RE = re.compile(r"^(#{1,6})(\s+.*)$")
COMMENT_HEADER = "<!-- Generated by scripts/generate_notebook_previews.py. Do not edit directly. -->"
INTRO = (
    "Open the full notebook in VS Code for the editable version. "
    "This in-deck preview is generated from the participant notebook because reveal.js "
    "does not render raw `.ipynb` embeds reliably in this workshop setup."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate static Quarto preview fragments from participant notebooks."
    )
    parser.add_argument(
        "notebooks",
        nargs="*",
        help="Optional notebook names to regenerate. Defaults to all participant notebooks.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    notebook_names = tuple(args.notebooks) if args.notebooks else NOTEBOOKS
    OUTPUT_DIR.mkdir(exist_ok=True)

    for notebook_name in notebook_names:
        notebook_path = ROOT_DIR / notebook_name
        if not notebook_path.exists():
            raise FileNotFoundError(f"Notebook not found: {notebook_path}")

        preview_path = OUTPUT_DIR / f"{notebook_path.stem}.preview.qmd"
        preview_path.write_text(render_preview(notebook_path), encoding="utf-8")
        print(f"Generated {preview_path.relative_to(ROOT_DIR)}")


def render_preview(notebook_path: Path) -> str:
    notebook = json.loads(notebook_path.read_text(encoding="utf-8"))
    parts = [
        COMMENT_HEADER,
        "::: {.notebook-preview}",
        f"### `{notebook_path.name}`",
        "",
        INTRO,
        "",
    ]

    for cell in notebook.get("cells", []):
        rendered = render_cell(cell)
        if rendered:
            parts.extend((rendered, ""))

    parts.append(":::")
    return "\n".join(parts).rstrip() + "\n"


def render_cell(cell: dict) -> str:
    source = normalize_source(cell.get("source", []))
    if not source.strip():
        return ""

    cell_type = cell.get("cell_type")
    if cell_type == "markdown":
        return demote_headings(source)
    if cell_type == "code":
        stripped_source, wrapped_prompt = unwrap_triple_quotes(source)
        language = detect_code_language(stripped_source, wrapped_prompt)
        if language == "bash":
            stripped_source = strip_notebook_shell_prefix(stripped_source)
        return f"```{language}\n{stripped_source.rstrip()}\n```"
    return ""


def normalize_source(source: list[str] | str) -> str:
    if isinstance(source, list):
        text = "".join(source)
    else:
        text = source
    return text.rstrip() + "\n"


def demote_headings(text: str, levels: int = 3) -> str:
    result = []
    for line in text.rstrip().splitlines():
        match = HEADING_RE.match(line)
        if match:
            heading_level = min(6, len(match.group(1)) + levels)
            result.append(f"{'#' * heading_level}{match.group(2)}")
        elif line == "---":
            # Markdown horizontal rules can be treated as slide boundaries in reveal.js.
            # Emit raw HTML instead so notebook section separators stay inside one slide.
            result.append("<hr />")
        else:
            result.append(line)
    return "\n".join(result)


def unwrap_triple_quotes(text: str) -> tuple[str, bool]:
    stripped = text.strip()
    for marker in ("'''", '"""'):
        if stripped.startswith(marker) and stripped.endswith(marker):
            inner = stripped[len(marker) : -len(marker)]
            return inner.strip("\n") + "\n", True
    return text, False


def detect_code_language(text: str, wrapped_prompt: bool) -> str:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if not lines:
        return "text"
    if wrapped_prompt:
        return "bash" if all(is_shell_line(line) for line in lines) else "text"
    if all(is_shell_line(line) for line in lines):
        return "bash"
    return "python"


def is_shell_line(line: str) -> bool:
    return line.startswith("!") or bool(SHELL_LINE_RE.match(line))


def strip_notebook_shell_prefix(text: str) -> str:
    stripped_lines = []
    for line in text.rstrip().splitlines():
        if line.startswith("!"):
            stripped_lines.append(line[1:])
        else:
            stripped_lines.append(line)
    return "\n".join(stripped_lines) + "\n"


if __name__ == "__main__":
    main()